### ISSUE TITLE
segmentation fault when I open this pdf

### ISSUE THREAD

**Issue by acgtyrant** [moosotc/llpp#104]
[Zhang 等。 - 2017 - Scale-Adaptive Convolutions for Scene Parsing.pdf](https://github.com/moosotc/llpp/files/2671813/Zhang.-.2017.-.Scale-Adaptive.Convolutions.for.Scene.Parsing.pdf)

The version is 30-1.

**Comment by moosotc** [comment]
Works just fine with master

~
- llpp -v
llpp v30-19-g0668f59, fitz 1.14.0, ocaml 4.07.1/64 bit
configuration file: /home/malc/.config/llpp.conf

**Comment by acgtyrant** [comment]
OK, I try to reproduce this phenomenon in the master.

**Comment by moosotc** [comment]
Have you updated your mupdf too? (via misc/getmupdf.sh for instance)
Is the problem reproducible via mupdf-x11(or gl)? (You would have to go
to build/mupdf and do a `make build=native' since getmupdf.sh doesn't
build mupdf  applications (only libraries)) FWIW i'v tried your config file
still no crash here)
