### ISSUE TITLE
what is page bias ?

### ISSUE THREAD

**Issue by Fandekasp** [moosotc/llpp#111]
Sorry for the newbie question, but what is the "set page bias" option supposed to do ?

Thank you for making llpp, feels like a liberation after sticking to mupdf for years :)

**Comment by moosotc** [comment]
Adrien Lemaire <notifications@github.com> writes:

> Sorry for the newbie question, but what is the "set page bias" option
> supposed to do ?

Sometimes documents are prepared in such a way that they contain
references to "raw" page numbers (for example "see page 10"), but in
reality the relevant information is on page 11 (due to cover pages or
whatnot) so you can set page bias (to say 2) and '11g' will take that
into account and bring you to age 13 skipping those "cover" pages.

Not sure if this explanation makes sense to you.

>
> Thank you for making llpp, feels like a liberation after sticking to
> mupdf for years :)

You are most welcome :)

-- 
mailto:moosotc@gmail.com

**Comment by Fandekasp** [comment]
totally makes sense, thanks a lot, quite useful !
