### ISSUE TITLE
slow opening pdf files with page size errors

### ISSUE THREAD

**Issue by szhang104** [moosotc/llpp#123]
I noticed that the loading time is much longer than other viewers (evince, mupdf for example) when the file contains errors. For example, [this file](https://gofile.io/?c=sJBR5l).

Version info:
OS: 
`Linux elhe 5.3.5-arch1-1-ARCH`
llpp is built from git:
`llpp v31-9-ga232ae2-dirty, fitz 1.15.0, ocaml 4.09.0/64 bit`

**Comment by moosotc** [comment]
Shuai Zhang <notifications@github.com> writes:

> I noticed that the loading time is much longer than other viewers
> (evince, mupdf for example) when the file contains errors. For
> example, [this file](https://gofile.io/?c=sJBR5l).
>
>
> Version info:
> OS: 
> `Linux elhe 5.3.5-arch1-1-ARCH`
> llpp is built from git:
> `llpp v31-9-ga232ae2-dirty, fitz 1.15.0, ocaml 4.09.0/64 bit`

The slowdown is due to error messages overwhelming list view, will try
to investigate the root cause, thanks for heads up.

In the mean time one can paper over the issue by:

index ab9c200..a59db9d 100644
--- a/link.c
+++ b/link.c
@@ -778,8 +778,9 @@ static void initpdims (void)
                 else {
                     if (empty) {
                         if (fz_is_empty_rect (rootmediabox)) {
-                            printd ("emsg cannot find page size for page %d",
-                                    pageno);
+                            if (0)
+                                printd ("emsg cannot find page size for page %d",
+                                        pageno);
                         }
                         else {
                             mediabox = rootmediabox;
