### ISSUE TITLE
How to use clipboard

### ISSUE THREAD

**Issue by luckyCoderLi** [moosotc/llpp#126]
Could can i select words to use from documents?

**Comment by moosotc** [comment]
彬 <notifications@github.com> writes:

> Could can i select words to use from documents?

I do not understand what you are asking. FWIW double clicking will
select a word.

**Comment by luckyCoderLi** [comment]
thanks,I select some words but those not location first in clipboard ,those location second in clipboard

**Comment by moosotc** [comment]
彬 <notifications@github.com> writes:

> thanks,I select some words but those not location first in clipboard
> ,those location second in clipboard

I, once again, do not understand what you.

**Comment by clockworkmurderer** [comment]
What he's trying to say is that when you select text from a document in llpp, the selection doesn't seem to consistently be placed at the top of the clipboard. I just had to manually clear the clipboard via the KDE Plasma clipboard widget because my selections were appearing at the end as if they were the oldest items instead of the expected behavior, which is that they appear at the top. Clearing the clipboard seems to have fixed it, but likely only temporarily.

**Comment by moosotc** [comment]
clockworkmurderer <notifications@github.com> writes:

> What he's trying to say is that when you select text from a document
> in llpp, the selection doesn't seem to consistently be placed at the
> top of the clipboard. I just had to manually clear the clipboard via
> the KDE Plasma clipboard widget because my selections were appearing
> at the end as if they were the oldest items instead of the expected
> behavior, which is that they appear at the top. Clearing the clipboard
> seems to have fixed it, but likely only temporarily.

When you select text and release the mouse button the text that is
selected will be piped through the selection-command, llpp itself is
blissfully unaware of what the selection command does.

Default command on X11 is xclip [1] one can test how it behaves by just
echoing stuff to it in the terminal... (no idea how KDE Plasma works
sorry)

[1] https://github.com/moosotc/llpp/blob/master/genconfstr.sh#L110
