### ISSUE TITLE
Utilize linker garbage collection to reduce executable size

### ISSUE THREAD

**Issue by Ristovski** [moosotc/llpp#159]
mupdf already seems to use `-fdata-sections`, `-ffunction-sections` when building the static library.

It would be nice if `llpp` used `-Wl,--gc-sections` when linking to remove unneeded mupdf cruft (I've looked and it does not seem to do this)

As of now, the built `llpp` binary weighs in at 40MB, running https://github.com/google/bloaty over it shows the following:
```
    FILE SIZE        VM SIZE    
 --------------  -------------- 
  77.6%  30.9Mi  82.5%  30.9Mi    [section .data]
   7.7%  3.07Mi   8.2%  3.07Mi    [section .text]
   2.3%   931Ki   2.4%   911Ki    parsing.c
   1.7%   709Ki   0.0%       0    [Unmapped]
   1.3%   523Ki   1.0%   371Ki    ./link.c
[SNIPPED]
```
This shows that it seems to bundle 30MB of what I guess is the mupdf static library.

**Comment by HinTak** [comment]
Not necessarily. Pdf viewer in

**Comment by HinTak** [comment]
The libmupdf.a shipped by fedora is 56MB, and linking against it (I am just lazy...) and not doing anything special gives a 14MB llpp binary. So that's about right. Strip'ing cut it down to 5MB but the binary becomes broken.

The system mupdf / mupdf-gl binary is 4 / 4.5 MB which are strip'ed. So there is probably a way of stripping the llpp binary down to about 5MB without breaking it. I suspect changes in linker flags are not involved/needed...

**Comment by HinTak** [comment]
Apparently the way llpp is built, (ocamlc -custom), bundles ocaml bytecode, means it should not be strip'ed. Since my striped outcome is similar in size to mupdf / mupdf-gl striped themyself, I consider my vanilla llpp build outcome, 12.4MB, reasonable, and I don't need to do anything about linker flags.

I think you need to check why your build is 40 MB!

**Comment by Ristovski** [comment]
Hmm, interesting finds! I will do some more testing over the weekend/next week (when I have free time) and report back with anything I find!

**Comment by moosotc** [comment]
FWIW ~40M is what i have too. release build of mupdf-x11 is 36M

**Comment by HinTak** [comment]
@moosotc @Ristovski heehee, I worked out the issue, it is as I initially replied: mupdf, by-default, bundle two very large CJK fonts as a static array. SourceHanSerif-Regular.ttc is 25MB, DroidSansFallbackFull.ttf and DroidSansFallback.ttf comes to 9MB. So that's 33MB+ gone! and striping has no effect on your 36MB mupdf-x11 , as they are "needed". 

What you could do, is to disable that functionality, together with USE_SYSTEM_LIBS=yes (which saves about 2MB by using the system libraries like harfbuzz/freetype etc, but you need -lfreetype etc for llpp in such case). If I do:

```
make OS=Linux build=release USE_SYSTEM_LIBS=yes XCFLAGS='-DTOFU -DTOFU_NOTO -DTOFU_CJK'
```

Then I still get a 49MB libmupdf.a, but all my mutool/mupdf-* are about 4MB.

FYI, the fedora mupdf build package plus build logs are here:
https://koji.fedoraproject.org/koji/buildinfo?buildID=1714801 , and they have some of the -DTOFU... switches. These are documented in `source/fitz/noto.c` .

consider adding `XCFLAGS='-DTOFU -DTOFU_NOTO -DTOFU_CJK'` to your mupdf build script.

**Comment by HinTak** [comment]
Fedora's mupdf package was built with '-DTOFU -DTOFU_CJK' but not '-DTOFU_NOTO' .

**Comment by Ristovski** [comment]
@HinTak Good job on figuring this out!

It never occurred to me that all the stuff in .data was actually the bundled fonts!

**Comment by HinTak** [comment]
It isn't too much "figuring" - I just checked that, the whole of 17 years of mupdf history does not have any commit from me. But I worked on a big part of ghostscript (the same people who wrote mupdf) about 10 years ago. So I was at least familiar with the organization's overall marketing material, and the specific claim that mupdf is the smallest pdf viewer there is, and is functional at about 4MB, and **can be made even smaller** down to 2MB(?) if you supply the fonts. The last time I pulled was 5 years ago though, a few months before SourceHanSerif-Regular.ttc was included, so I only remembered the 10-20 MB DroidSans being a large part of the binary's size, which was ~15MB then. It is more a matter of catching up after 5 years and finding out details I was once quite familiar in an overview sense.

**Comment by HinTak** [comment]
I am wonderimg whether those options should be on for llpp . Fedora obviously decided that, people want fast/small pdf viewing can live without CJK support.

**Comment by moosotc** [comment]
HinTak ***@***.***> writes:

> I am wonderimg whether those options should be on for llpp . Fedora
> obviously decided that, people want fast/small pdf viewing can live
> without CJK support.

Not by default. Testing matrix increases.

**Comment by HinTak** [comment]
Fair enough. Afaik, they are used for documents without embedded CJK font (subsets). The pdf specification only mandates that viewers must provide the base 14 (Times roman/italic/bold/bold italic, Helvetica x4, courier x4, symbols, wingding(?)); even for Adobe acrobat viewer, CJK support is or was an additional pack. And pdfs tend to have required CJK fonts embedded (thus not needing them in the viewer). Mupdf - as a document rendering library - has it mainly for the ebook usage.

**Comment by Ristovski** [comment]
Perhaps the sanest solution to this would be to allow `llpp` to either pick up the system `mupdf` lib if its detected at build time, or allow passing cflags to `mupfd` when its being built.

**Comment by moosotc** [comment]
Rafael Ristovski ***@***.***> writes:

> Perhaps the sanest solution to this would be to allow `llpp` to either
> pick up the system `mupdf` lib if its detected at build time, or allow
> passing cflags to `mupfd` when its being built.

First variant means that one can somehow know what options system mupdf
was built with and, consequently, which libraries are needed. Second
(mupdf build flags) appears to be more tractable.

**Comment by moosotc** [comment]
HinTak ***@***.***> writes:

> Fair enough. Afaik, they are used for documents without embedded CJK
> font (subsets). The pdf specification only mandates that viewers must
> provide the base 14 (Times roman/italic/bold/bold italic, Helvetica
> x4, courier x4, symbols, wingding(?)); even for Adobe acrobat viewer,
> CJK support is or was an additional pack. And pdfs tend to have
> required CJK fonts embedded (thus not needing them in the
> viewer). Mupdf - as a document rendering library - has it mainly for
> the ebook usage.

I've asked mupdf developers on IRC, here's the transcript:

<malc_> ator, sebras: how accurate is the assertion (regarding primary use of
        CKJ fonts) made here
        https://github.com/moosotc/llpp/issues/159#issuecomment-796576452 ?
                                                                        [12:00]
[...]

<ator> fairly accurate, but ignore the large swathes of semi-broken PDF files
       out in the wild that don't embed their CJK fonts (or any fonts for that
       matter) assuming that Acrobat can find the Windows fonts they rely on
                                                                        [13:54]
<ator> if you don't care about pretty, but still want these files to be
       legible, you can do -DTOFU_CJK_EXT to pick the smallest
       DroidSansFallback font (no language variants, only the common character
       sets, sans serif and as small as you can get)  [13:56]
<ator> -DTOFU and -DTOFU_CJK_EXT is the smallest but still fully functional
       you can get, but somewhat crippling the epub (it now has to rely on the
       base14 fonts and the cjk font and can only do latin/greek/cyrillic/cjk)
                                                                        [13:57]

**Comment by HinTak** [comment]
Cool. "-DTOFU and -DTOFU_CJK_EXT" would be without the 25MB SourceHanSerif-Regular.ttc so that's a big size improvement, and still being able to read most pdfs okay.
