### ISSUE TITLE
Prebuilded realeses

### ISSUE THREAD

**Issue by leiserfg** [moosotc/llpp#44]
It's a wish: Can you please share a builded version of llpp? I'm a debian user and is cumbersome to me building llpp (the version of ocaml in debian is old).

**Comment by moosotc** [comment]
Leiser Fernández Gallo <notifications@github.com> writes:

> It's a wish: Can you please share a builded version of llpp? I'm a
> debian user and is cumbersome to me building llpp (the version of
> ocaml in debian is old).

Well, I definitely do not want to do this, chances that my locally
compiled version would work for other people are rather slim (given
that the Linux distribution I'm using is kind-of bleeding edge).

I just did a:

\time -p sh -c 'sh ./configure -prefix $HOME/tmp/ocaml-git; make world.opt install'

inside ocaml's git checkout and after

real 275.73
user 243.34
sys 23.07

got a git HEAD of ocaml built and installed into temporary location.

Then inside llpp checkout

PATH=$HOME/tmp/ocaml-git/bin:$PATH \time -p sh build.sh build-ocaml-git

real 4.23
user 3.83
sys 0.38

So even without parallelism (i.e. building ocaml and llpp with just one
core) it took less than 5 minutes.

It would be lovely to have llpp in Debian, Ubuntu, Fedora, whatnot - but
sadly I have no control or influence over that.

It's worth mentioning that due to the way mupdf works (by default)
(i.e. font's are compiled into the library and by extension the binary
that uses the library) it's size is humongous:

$ du -bh llpp
38M llpp

(One might argue that the times when 40M was considered large have long
gone, but I have no place to distribute such beasts without feeling
weird)

-- 
mailto:moosotc@gmail.com

**Comment by leiserfg** [comment]
I did it and it was easier than building libmupdf itself, thanks.
